Repository TNTU-RS-internship/scalhive-theme, pull requests merged in 2024-01, with the labels that each got.

#8 Fix module path
  .gitignore
  go.mod
  package.hugo.json
  package.json
Labels: bug

#19 Updated main page structure
  layouts/index.html
Labels: enhancement

#20 Stylize contact page form
  assets/ananke/css/_styles.css
  assets/ananke/css/_tachyons.css
  layouts/_default/section-image.html
  layouts/partials/contacts-with-google-form.html
  layouts/partials/img-figure.html
Labels: enhancement

#22 Edit footer structure
  assets/ananke/css/_styles.css
  assets/ananke/socials/email.svg
  layouts/partials/site-footer.html
Labels: enhancement

#23 Change main page layout component
  layouts/index.html
Labels: enhancement

#28 11 edit image components style for main page
  assets/ananke/css/_styles.css
  layouts/partials/image-srcset.html
  layouts/partials/img-figure.html
Labels: enhancement

#24 Stylyzed blog pages
  layouts/_default/section-image-right.html
  layouts/_default/single.html
  layouts/_default/summary-with-image.html
  layouts/_default/summary.html
  layouts/blog/list.html
Labels: enhancement

#30 29 change font family and make some hotfixes
  assets/ananke/css/_styles.css
  layouts/index.html
  layouts/page/single.html
  layouts/partials/i18nlist.html
  layouts/partials/img-left-plus-right.html
  layouts/partials/img-left.html
  layouts/partials/img-right.html
  layouts/partials/page-header.html
  layouts/partials/site-header.html
Labels: enhancement

#31 17 stylize website
  assets/ananke/css/_styles.css
  assets/ananke/css/_tachyons.css
  assets/ananke/socials/email.svg
  layouts/_default/section-image-right.html
  layouts/_default/single.html
  layouts/_default/summary-with-image.html
  layouts/_default/summary.html
  layouts/blog/list.html
  layouts/index.html
  layouts/page/single.html
  layouts/partials/i18nlist.html
  layouts/partials/image-srcset.html
  layouts/partials/img-figure.html
  layouts/partials/img-left-plus-right.html
  layouts/partials/img-left.html
  layouts/partials/img-right.html
  layouts/partials/page-header.html
  layouts/partials/site-footer.html
  layouts/partials/site-header.html
  layouts/partials/site-navigation-mobile.html
  layouts/partials/site-navigation.html
  static/js/navigation.js
Labels: enhancement

#35 32 change components styles for blog page
  assets/ananke/css/_styles.css
  layouts/blog/list.html
  layouts/index.html
  layouts/page/single.html
  layouts/partials/contact-us-btn.html
  layouts/partials/page-header.html
  layouts/partials/site-header.html
  layouts/partials/site-navigation-mobile.html
  layouts/partials/site-navigation.html
  static/js/current-page.js
Labels: enhancement

#38 Add tagging policy
  README.md
Labels: documentation

#39 33 stylize texts font
  assets/ananke/css/_styles.css
  layouts/_default/baseof.html
  layouts/_default/list.html
  layouts/_default/section-image-left.html
  layouts/_default/section-image-right.html
  layouts/_default/single.html
  layouts/_default/summary-with-image.html
  layouts/blog/list.html
  layouts/index.html
  layouts/page/single.html
  layouts/partials/contacts-with-google-form.html
  layouts/partials/head-additions.html
  layouts/partials/image-srcset.html
  layouts/partials/img-figure.html
  layouts/partials/img-left-plus-right.html
  layouts/partials/img-left.html
  layouts/partials/little-icons.html
  layouts/partials/page-header.html
  layouts/partials/site-footer.html
  layouts/partials/site-header.html
  layouts/partials/to-main-page-btn.html
  static/js/current-page.js
Labels: enhancement

#41 33 stylize info components
  assets/ananke/css/_styles.css
  layouts/404.html
  layouts/_default/baseof.html
  layouts/_default/list.html
  layouts/_default/section-image-left.html
  layouts/_default/section-image-right.html
  layouts/_default/single.html
  layouts/_default/summary-with-image.html
  layouts/blog/list.html
  layouts/index.html
  layouts/page/single.html
  layouts/partials/contacts-with-google-form.html
  layouts/partials/head-additions.html
  layouts/partials/image-srcset.html
  layouts/partials/img-figure.html
  layouts/partials/img-left-plus-right.html
  layouts/partials/img-left.html
  layouts/partials/little-icons.html
  layouts/partials/page-header.html
  layouts/partials/site-footer.html
  layouts/partials/site-header.html
  layouts/partials/to-main-page-btn.html
  static/js/current-page.js
Labels: enhancement
