Repository TNTU-RS-internship/scalhive-theme, pull requests merged in 2024-07, with the labels that each got.

#47 Fix google maps link
  layouts/partials/site-footer.html
Labels: enhancement

#49 Change style for privacy page
  assets/ananke/css/_styles.css
  layouts/page/single.html
Labels: enhancement

#51 Add translation to confirm cookies banner
  layouts/partials/consent.html
Labels: enhancement

#52 Add tranlation to confirm cookies banner
  layouts/partials/consent.html
Labels: enhancement

#53 Implement Google Analytics and Cookies
  layouts/_default/baseof.html
Labels: enhancement

#54 Fix cookies
  layouts/_default/google_analytics.html
  layouts/partials/consent.html
Labels: bug

#55 Fix buttons
  assets/ananke/css/_social-icons.css
  layouts/partials/site-footer.html
Labels: enhancement

#56 Add dockerhub logo
  assets/ananke/socials/dockerhub.svg
Labels: bug

#57 45 fix cookies
  layouts/_default/baseof.html
  layouts/_default/google_analytics.html
  layouts/partials/consent.html
  static/js/google_analytics.js
Labels: bug

#59 Fix style bugs
  assets/ananke/css/_social-icons.css
  layouts/partials/contact-us-btn.html
  layouts/partials/site-footer.html
Labels: invalid

#60 Fix redirects
  layouts/404.html
  layouts/page/single.html
  layouts/partials/i18nlist.html
Labels: bug

#62 Remove resize
  layouts/partials/contacts-with-google-form.html
Labels: enhancement

#65 Fix styles
  assets/ananke/css/_styles.css
  layouts/blog/list.html
  layouts/index.html
  layouts/page/single.html
  layouts/partials/consent.html
  layouts/partials/contact-us-btn.html
  layouts/partials/contacts-with-google-form.html
  layouts/partials/img-left-plus-right.html
  layouts/partials/page-header.html
  layouts/partials/site-header.html
Labels: bug

#66 Add border lines
  layouts/_default/single.html
  layouts/page/single.html
  layouts/partials/img-right.html
Labels: enhancement

#68 Change Google Analytics to Google Tag Manager
  layouts/_default/baseof.html
Labels: enhancement
